plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.14'
}

javafx {
    version = '21'
    modules = [ 'javafx.controls' ]
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fazecast:jSerialComm:2.10.4'
}

application {
    mainClass = 'cnc.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}